### ISSUE TITLE
stestr run --subunit does not work

### ISSUE THREAD

**Issue by MaciejKucia** [mtreinish/stestr#101]
Similar to https://github.com/mtreinish/stestr/pull/93

When `--subunit` parameter is provided, output is _pretty-plaintext_.
`stestr last --subunit` works correctly

**Comment by mtreinish** [comment]
yep, that's definitely not working as expected. After taking a quick look at the stestr run code I'm guessing this is an issue in stestr load since it looked like the subunit_out param was being passed everywhere properly. I'll keep digging but if you know where this is going wrong feel free to push a patch up.

**Comment by masayukig** [comment]
This bug should be fixed with that commit. If there's something wrong, reopen this issue.
