### ISSUE TITLE
Enable to show the license on GitHub

### ISSUE THREAD

**Issue by masayukig** [mtreinish/stestr#125]
I've noticed that the GitHub has a feature to show the license of the project[1]. The help looks like just says adding a license file is enough for it. We already have it[2], of course. However, the license doesn't show up on the page.
I'm not sure how to do it, actually. But it shouldn't be so hard. In the worse case, just delete the LICENSE file, and then, do the thing help[1] says.

This page[3] also explains the feature. I couldn't find the solution for this, though.

[1] https://help.github.com/articles/adding-a-license-to-a-repository/
[2] https://github.com/mtreinish/stestr/blob/master/LICENSE
[3] https://help.github.com/articles/licensing-a-repository/

**Comment by mtreinish** [comment]
I've noticed this too, but have no idea how to make it pop pu in the UI. I always assumed it was either something with the formatting in the license file preventing github from detecting it properly. Or because the license wasn't always just Apache 2.0 (it used to be a dual licensed Apache and BSD, and I re-licensed it as derivative work in: https://github.com/mtreinish/stestr/commit/ff96eea0fcc892e772cc084471db6eff82d9a86b#diff-9879d6db96fd29134fc802214163b95a and github is looking at the history and realizing this. (although this is probably pretty unlikely)

**Comment by masayukig** [comment]
hmm, it's not so easy than I expected.. :(

I just checked the license with licensee[1], that says "Apache License 2.0" with 100% confidence :) 
```
$ licensee.ruby2.4
License: Apache License 2.0
Matched files: ["LICENSE"]
LICENSE:
  Content hash: d7bc6f56cd49606d0134945d4b91ae47d3cee458
  Confidence: 100.00%
  Matcher: Licensee::Matchers::Exact
  License: Apache License 2.0
```

The help page says,
```
To have your license detected, simplify your LICENSE file and note the complexity somewhere else, such as your repository's README file.
```
I don't know how to for this more.. It's already simple enough.

[1] https://help.github.com/articles/licensing-a-repository/#detecting-a-license

**Comment by mtreinish** [comment]
Maybe you should send an email to github support, because if the tool that they say that they're using is saying it's a 100% match maybe it's a bug in github and not something on our end?

**Comment by masayukig** [comment]
yeah, indeed. I'll do that :)

**Comment by masayukig** [comment]
I submitted a help request and I've got a reply from github support. That said the support has triggered  a detection process manually. And now, we can see the license on the page :)

So, I'll close this issue.
