### ISSUE TITLE
Add config/cli flag to group tests by class

### ISSUE THREAD

**Issue by mtreinish** [mtreinish/stestr#198]
### Issue description

Currently we only support dynamic grouping (ignoring manual scheduling) via a grouping regex. This is fine and very flexible, but it's tricky to construct a regex that works exactly as needed. A common use case is that a test suite needs to be parallelize on the test class and not individual methods/test_ids. This is currently accomplishable by just setting the group_regex to: `([^\.]*\.)*`. But, it would probably be easier/better to add a new option to the stestr.conf and cli to split at the class level so people don't need to remember that regex.

I'm just not sure of the best name for that --parallel-class or something?

Also something we'll have to put some thought and discussion behind is the priority of arguments. Like does --parallel-class (or whatever we call it) take priority over group_regex. Also between parallel-class in a config file and --group-regex on the cli (and vice versa)

**Comment by mtreinish** [comment]
@masayukig do you have any thoughts on this? Also can I assign this to you? I think it should be pretty simple (we just need to define the behavior) but I probably won't be able to get to the implementation for a little while.

**Comment by masayukig** [comment]
That looks a good option/flag to me. Since stestr is a parallel test runner, I think it's natural to have like that option.
And I'm happy to take this :)

And regarding the priority, I agree with you, like this.
* CLI option > config file
* `parallel-class` > `group-regex`

But some corner cases are like these? :
* `--group-regex` on the CLI > `parallel-class` in a config file
* `--parallel-class` on the CLI > `group-regex` in a config file (This is no doubt, though.)

And also, I think we should **forbid** to specify:
* `--group-regex` and `--parallel-class` on the CLI

and/or

* `group-regex` and `parallel-class` in a config file
 at the same time? 

And, we should **allow** to specify `--group-regex` on the CLI and `parallel-class` in a config file (and vice versa), right?

**Comment by mtreinish** [comment]
Yeah, I agree with everything you outlined there. Yep, I agree we should allow setting `--group-regex` on the cli and have that overrides `parallel-class` in the config file (and vice versa). I think that makes sense, so you can have local overrides of what's configured for the repo.

As for the having both in the config file that is an interesting case. I don't think we have mutually exclusive options like that in the stestr conf today. Do you think we should fail if both are set in the config file? Or should we go with parallel class taking priority over group-regex (and we just ignore the group regex)?

**Comment by masayukig** [comment]
Hm, yeah, we don't have like mutually exclusive options on the CLI options too (e.g. `--serial` and `--concurrency`). I was thinking we should fail if both are set in the config file because it makes users not be confused with that combination if the user set both.
But I also think we don't need to be so strict for like that thing now.

So, my conclusion is we'll just go with parallel-class taking priority over group-regex (just ignore the group-regex, no fail).

**Comment by mtreinish** [comment]
Ok that works for me, I don't really have a preference. As long as we clearly document whatever behavior you choose since we'll be using that as the interface for a long time. I think it's a pretty weird edge case where you say that you want to group by class name and also group by regex in the config file.
