### ISSUE TITLE
unorderable types: str() < int()

### ISSUE THREAD

**Issue by tbreeds** [mtreinish/stestr#231]
### Issue description

The 2.3.0 stestr release fails with "unorderable types: str() < int()" [1]

We believe this is due to: https://github.com/mtreinish/stestr/pull/208

### Additional information

[1] http://logs.openstack.org/79/640579/2/check/neutron-grenade-multinode/b56b183/job-output.txt.gz#_2019-03-03_06_00_19_638638

**Comment by mtreinish** [comment]
I just pushed the the 2.3.1 release which includes this fix. Thanks for both identifying it and proposing the fix Tony. Sorry it took so long to address it.

**Comment by stmcginnis** [comment]
"I just pushed the the 2.3.1 release which includes this fix." Did that not actually make it? According to comments in https://github.com/mtreinish/stestr/issues/235, it doesn't appear so.

**Comment by mtreinish** [comment]
It did, but then ostestr was broken in another (similar) way because it was passing None (which is also not an int like the documented api) for it's concurrency value by default. The commit to translate None -> 0, #233 , was not included in the 2.3.1 release because it wasn't found until after the release.

**Comment by stmcginnis** [comment]
Got it, thanks @mtreinish
