### ISSUE TITLE
Issue with stestr 2.5.0 using Python 3.4

### ISSUE THREAD

**Issue by aseure** [mtreinish/stestr#264]
### Issue description

On one of our projects for which we use `tox` to run our tests against different versions of Python, our Python 3.4 test is consistently failing. From the following trace, we identified the issue came [from this line](https://github.com/mtreinish/stestr/commit/c50a9a70b3a723d4ccaf12b0dfc4a6a745ec2337#diff-b1dc26084457524f8efa9922f12e0bb0R65) added in https://github.com/mtreinish/stestr/commit/c50a9a70b3a723d4ccaf12b0dfc4a6a745ec2337 between 2.4.0 and 2.5.0.

<img width="1280" alt="Screenshot 2019-08-15 at 09 38 45" src="https://user-images.githubusercontent.com/3115191/63110665-d8f11080-bf40-11e9-8a7f-6608c349fa61.png">

We are aware of Python 3.4 deprecation, as per [PEP-429](https://www.python.org/dev/peps/pep-0429/) but since we are shipping a library, we cannot deprecate Python 3.4 immediately.

#### Expected behavior and actual behavior

- Expected behavior: no error running `stestr` with Python 3.4
- Actual behavior: no error running `stestr` with Python 3.4

#### Steps to reproduce the problem

- Run a test with Python 3.4 using `stestr` at version 2.5.0

#### Specifications like the version of the project, operating system, or hardware

- Python 3.4
- MacOS and Linux
- `stestr` 2.5.0

### System information

**stestr version (`stestr --version`):**
2.5.0

**Python release (`python --version`):**
Python 3.4

**pip packages (`pip freeze`):**
N/A

**Comment by mtreinish** [comment]
Hmm, we actually stopped advertising support for python 3.4 back in the 1.1.0 release IIRC and stopped actively testing anything with 3.4 as part of development of 2.0.0. That being said I'm not against coming up with a workaround for the 3.4 case here. The switch to using a stdlib runner while fixing a **huge** number of issues for python >=3.5 hasn't been as smooth a roll out as I hoped, so I wouldn't be opposed to adding a workaround to still enable 3.4 to run even if it's not officially supported or tested. I think the best way to do that here would be to change the if logic here:

https://github.com/mtreinish/stestr/blob/master/stestr/subunit_runner/run.py#L87 

to use the new custom test runner if >=python 3.5 (instead of just if python3 like it is now), Then for python 3.4 and python 2.7 it'll fallback to using the testtools based runner that was used in stestr 2.4.0. Does that sound like a good plan?

**Comment by mtreinish** [comment]
Oh, also while only somewhat related, on the python 3.4 support front I also should point out that we're planning a 3.0.0 release at some point in early 2020, this will completely drop python 2 support and as part of that we're going to define the minimum python 3 version in the package metadata as 3.5 (https://github.com/mtreinish/stestr/blob/remove-python2-support/setup.cfg#L26 ). Just something to keep in mind moving forward.

**Comment by mtreinish** [comment]
@aseure can you verify that #265 will fix this issue for you. If so I'll go ahead and merge it and push a 2.5.1 release out shortly (there is another bug with the new runner I'd like to try and come up with a workaround for in that release too).

**Comment by aseure** [comment]
@mtreinish Thank you very much for all those details. For now, we can stick to version 2 until 2020 and version 3 is out. Thank you for letting us know about this change to come. I'm gonna try your branch right now.

**Comment by aseure** [comment]
@mtreinish Yes I confirm that #265 fixes the issue on my side, thanks!

**Comment by mtreinish** [comment]
Just a heads up I pushed `2.5.1` just now (and it should be up on pypi now too) that included the fix for this issue
