### ISSUE TITLE
pip installs latest version in python2.7 environment

### ISSUE THREAD

**Issue by Andrey-mp** [mtreinish/stestr#292]
**Issue description**

pip2 installs stestr of version 3.0.0 in python2.7 env. It happens cause pypi doesn't have metadata tag 'data-requires-python'. This happens cause setup.cfg has key 'requires-python' instead of 'python-requires'

**Expected behavior and actual behavior**
expected: version <3.0.0 will be install by pip2.
actual: version 3.0.0 is installed by pip2

**Steps to reproduce the problem**
Run docker's image centos:7 and after installing pip try to install stestr by pip.

**Specifications like the version of the project, operating system, or hardware**

**System information**
 - OS: centos:7
 - stestr version (`stestr --version`): 3.0.0
 - Python release (`python --version`): 2.7
 - pip packages (`pip freeze`): doesn't matter

**Additional information**

**Comment by Andrey-mp** [comment]
https://github.com/mtreinish/stestr/pull/293

**Comment by mtreinish** [comment]
We were discussing this issue earlier today on openstack-qa in IRC: http://eavesdrop.openstack.org/irclogs/%23openstack-qa/%23openstack-qa.2020-03-26.log.html#t2020-03-26T19:40:06

Based on this discussion it appears that the issue with python 2.7 is caused by a temporary pypi issue. Apparently pbr supports python `requires-python` and python-requires`. If this is not the case and we do need to update the package metadata (per #293) then I will push that out as 3.0.1 and you can just blacklist 3.0.0 in your py 2.7 package's requirements.

**Comment by gmannos** [comment]
'python-requires' support in there for sure  in pbr  - https://github.com/openstack/pbr/blob/9257b6843568052be1dc1a5f3df6f629795e08b2/pbr/util.py#L116

'python-requires' is introduced from PEP440 version and until PEP345 it used to support 'requires-python also 'https://www.python.org/dev/peps/pep-0345/#requires-python 

I am not finding enough evidence that 'requires-python' is still supported or it is being removed. still checking....

**Comment by Andrey-mp** [comment]
The tricky thing is that pypi really doesn't return that metadata.
Also I've checked latest pip in new centos:7 container. It installs version 3.0.0

**Comment by mtreinish** [comment]
3.0.1 has been pushed out with #293 applied

**Comment by Andrey-mp** [comment]
Thank you!
