### ISSUE TITLE
Encoding issue on Windows

### ISSUE THREAD

**Issue by 1ucian0** [mtreinish/stestr#295]
**Issue description**

While testing some ascii chars, I noticed that I'm getting an failed on stestr that passes in unittest. The problem seems connected with the encoding reported by the environment. This only happens on Windows (I tested on Linux and MacOS).

Consider the following example:
```python
from unittest import TestCase
import sys

class UtfChar():
    def __init__(self):
        self.encoding = sys.stdout.encoding

    def __str__(self):
        return "┌".encode().decode(self.encoding)

class TestUnicode(TestCase):
    def test_unicode(self):
        something = UtfChar()
        self.assertEqual(sys.stderr.encoding, "utf-8")
        self.assertEqual(sys.getfilesystemencoding(), "utf-8")
        self.assertEqual(sys.getdefaultencoding(), "utf-8")
        self.assertEqual("┌", str(something))
```

If runned with unittest, the test passes. It does not with stestr because the `sys.stdout.encoding` in the object constructor is set to `cp1252` instead of `utf-8` (as the windows cmd terminal). Notice that the `assertEqual(sys.stderr.encoding, "utf-8")` in the test passes. I added the other (passing) tests to check if was something related there... but nothing.

I think this is a bug because the result is different for unittest and stestr. However, I don't know why this happens. With `--serial` the problem persists.

**System information**
 - OS: Windows10
 - stestr version: 3.0.1
 - Python release: 3.7.7

**Comment by mtreinish** [comment]
After digging into this a bit there isn't anything for stestr to fix it's an issue with the windows environment configuration. To make utf8 work by windows you need to configure the windows code page to be utf8 as well as the bash env (assuming you're using bash on windows) locale to be utf8. (I also would try to tell python that files and pipes should be utf8 although it's unclear based on the documentation whether this changes anything [1])

For example, I made a small windows CI job configuration change in: https://github.com/Qiskit/qiskit-terra/pull/5988 to set utf8 for windows in bash to fix this issue reported.

Specifically running: `chcp.com 65001` from bash before running stestr to change the code page to utf8 and setting the env variables: `LANG="C.UTF-8"` and `PYTHONIOENCODING:="utf-8:backslashreplace"`

I'm going to close this as not something we can fix in stestr, since it's a windows environment issue. Please feel free to reopen this issue if this doesn't fix it for you or there is more to discuss here.

[1] https://docs.python.org/3/using/cmdline.html#envvar-PYTHONIOENCODING
