### ISSUE TITLE
Integrate with coverage

### ISSUE THREAD

**Issue by pshchelo** [mtreinish/stestr#97]
To be a more complete replacement for 'testrepository', stestr  should support setuptools integration (with coverage integration) as testrepository does 

http://testrepository.readthedocs.io/en/latest/MANUAL.html#setuptools-integration

**Comment by mtreinish** [comment]
I'm not sure if we want to do this. I've always viewed the testr setuptools integration (either exposed directly by testr or via pbr) as a problem because it makes things more confusing for end users. People don't really end up knowing where and how their tests are being run when you hide the test runner execution behind an external tool. (for a recent example: https://github.com/testing-cabal/testrepository/issues/31 ) IMO it would be better to just add any functionality to the stestr command and document how to use it.

It sounds like what you really want is a coverage flag for stestr so users don't have to explicitly set PYTHON=coverage run --parallel. I don't think we need to add a distutils.commands entrypoint just to do that though. Is there anything else you feel the setuptools integration buys us?

**Comment by pshchelo** [comment]
@mtreinish not really, coverage integration would be enough. Overriding PYTHON does seems weird, although doable using tox->stestr.

I'll change the issue title accordingly.

**Comment by mtreinish** [comment]
Well if you want to just do it in tox it's not that bad. For example what I did in shade:

https://github.com/openstack-infra/shade/blob/master/tox.ini#L47-L55

But I think integrating a coverage option into stestr is a good feature to add. Not sure when I can get around to implementing it myself, but feel free to push patches if you'd like to give it a try.

**Comment by masayukig** [comment]
Just FYI, I started to implement for this issue on my branch https://github.com/masayukig/stestr/tree/integrate-coverage

**Comment by masayukig** [comment]
@mtreinish heh, thanks :)

**Comment by masayukig** [comment]
@mtreinish So, my current implementation[0] is on #100 patch because I was expecting the cliff patch would be merged soon. But if you want this feature earlier, I'll change the patch.
Thoughts?

**Comment by masayukig** [comment]
Well, we decided to close this issue with this conversation at this moment. But if we change our minds again in the future, we can always reopen it. Any comments are welcome anytime.

https://github.com/mtreinish/stestr/pull/196#pullrequestreview-163859660
> That being said I have been thinking about this some more and wonder if this goes against the unix philosophy for stestr. stestr is a parallel python test runner and it should do that well, while coverage collection and reporting is the role of the coverage tool.
